import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
import { QueryProvider } from "@/components/providers/query-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const extensionHydrationCleanup = `
(() => {
  const attributes = [
    "fdprocessedid",
    "data-gr-ext-installed",
    "data-new-gr-c-s-check-loaded"
  ];
  const selector = attributes.map((attribute) => \`[\${attribute}]\`).join(",");

  function cleanElement(element) {
    for (const attribute of attributes) {
      element.removeAttribute(attribute);
    }
  }

  function clean(root = document) {
    if (root instanceof Element) {
      cleanElement(root);
    }

    document.documentElement && cleanElement(document.documentElement);
    document.body && cleanElement(document.body);
    root.querySelectorAll?.(selector).forEach(cleanElement);
  }

  clean();

  const observer = new MutationObserver((mutations) => {
    for (const mutation of mutations) {
      if (
        mutation.type === "attributes" &&
        mutation.attributeName &&
        attributes.includes(mutation.attributeName)
      ) {
        mutation.target.removeAttribute(mutation.attributeName);
      }

      for (const node of mutation.addedNodes) {
        if (node instanceof Element) {
          clean(node);
        }
      }
    }
  });

  observer.observe(document.documentElement, {
    attributeFilter: attributes,
    attributes: true,
    childList: true,
    subtree: true
  });

  window.addEventListener(
    "load",
    () => setTimeout(() => observer.disconnect(), 1000),
    { once: true }
  );
})();
`;

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col" suppressHydrationWarning>
        <Script
          id="extension-hydration-cleanup"
          strategy="beforeInteractive"
          dangerouslySetInnerHTML={{ __html: extensionHydrationCleanup }}
        />
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
